---
title: "mp-diagnostics"
author: "Brie Sherow"
date: "12/07/2020"
output: html_document
---

```{r setup, echo=FALSE, include=FALSE}
knitr::opts_chunk$set(fig.path="output/", fig.width=11, fig.height=9.5, fig.align="center")
```

```{r load library, include=FALSE}
library(bibliometrix)
```

```{r upload data, eval=TRUE}
getwd()
# bib <- convert2df(file = c("./data/scopus2015-2017.bib"), dbsource = "scopus", format = "bibtex") # Testing using one bib file

bib <- convert2df(file = c("./data/scopus2018-2019.bib","./data/scopus2015-2017.bib", "./data/scopus2011-2014.bib","./data/scopus2006-2010.bib", "./data/scopus1999-2005.bib","./data/scopus1970-1998.bib"), dbsource = "scopus", format = "bibtex") # Convert to a bibliometric data frame
# names(bib)
# write.csv(bib, "output/bib_as_df.csv", row.names = FALSE) #save this data frame as a csv file
```

```{r get author names, eval=TRUE}
# head(bib$AU) #have a look at the few few records on your sceen
authors <- bib$AU
authors <- unlist(strsplit(authors, ";")) #split the records into individual authors
authors <- authors[order(authors)] #order alphabetically
head(authors) #have a look again

#write.csv(authors, "output/author_list_uncleaned.csv", row.names = FALSE) #if you want to save this data frame as a csv file
```

```{r analysis and summary}
results <- biblioAnalysis(bib, sep=";")

options(width=100)
S <- summary(object = results, k = 10, pause = FALSE)
```

```{r summary plots}
plot(x=results, k=10, pause=F)
```

```{r top authors over time}
topAU <- authorProdOverTime(bib, k=50, graph=T)

#separating the lists into df to save as csv
dfAU <- print(topAU$dfAU)

dfPapersAU <- print(topAU$dfPapersAU)

write.csv(dfAU, "output/AUcitations.csv", row.names = FALSE) #save this data frame as a csv file

write.csv(dfPapersAU, "output/AUpapercitations.csv", row.names = FALSE) #save this data frame as a csv file
```

```{r  most cited papers, eval=TRUE}
mostcitedP <- citations(bib, field = "article", sep = ";")
cbind(mostcitedP$Cited[1:50]) #first 50
write.csv(mostcitedP, "output/mostcitedP.csv", row.names = FALSE) #save this data frame as a csv file
```

**Bibliographic coupling** - two articles are bibliographically coupled if they share at least one reference from their reference lists (i.e. at least one cited source appears in the reference lists/bibliographies of both papers (Kessler, 1963).  

```{r  paper coupling network, eval=TRUE}
#Looking at papers
BCNetMatrix <- biblioNetwork(bib, analysis = "coupling", network = "references", sep = ";")
BCnet = networkPlot(BCNetMatrix, weighted = NULL, n = 50, Title = "Papers' bibliographic coupling", type = "fruchterman", size = 5, remove.multiple = TRUE, labelsize = 0.5)
```

**Keyword co-occurrences** - we can also visualise which papers share most keywords (from Scopus database).    

```{r  keyword co-occurance network, eval=TRUE}
#Looking at topics
TNetMatrix <- biblioNetwork(bib, analysis = "co-occurrences", network = "keywords", sep = ";")
Tnet = networkPlot(TNetMatrix, n = 30, Title = "Keyword co-occurance", type = "fruchterman", size = T, remove.multiple = FALSE, labelsize = 0.7, edgesize = 5)
```

```{r  conceptualStructure map, eval=TRUE}
#Authors keywords
DE_CS <- conceptualStructure(bib, field = "DE", minDegree = 20, k.max = 2, stemming = FALSE, labelsize = 10)

```
