---
title: "mp-mapping"
author: "Brie Sherow"
date: "08/07/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

```

```{r figure-setup, echo=FALSE, include=FALSE}
knitr::opts_chunk$set(fig.path="output/", fig.width=11, fig.height=9.5, fig.align="center")
#reference:https://geocompr.robinlovelace.net/adv-map.html#static-maps
```

```{r install tmap and load data}
# install.packages("tmaptools")
# install.packages("tmap")
library(tmaptools)
library(tmap)
library(sf)
library(bibliometrix)
data("World")
```


```{r upload data, eval=TRUE}
# getwd()
# bib <- convert2df(file = c("./data/scopus2015-2017.bib"), dbsource = "scopus", format = "bibtex") # Convert one file to biblio df for testing

bib <- convert2df(file = c("./data/scopus2018-2019.bib","./data/scopus2015-2017.bib", "./data/scopus2011-2014.bib","./data/scopus2006-2010.bib", "./data/scopus1999-2005.bib","./data/scopus1970-1998.bib"), dbsource = "scopus", format = "bibtex") # Convert all files to a bibliometric data frame

# names(bib)

#write.csv(bib, "output/bib_as_df.csv", row.names = FALSE) #save this data frame as a csv file
```

```{r analysis and summary}
results <- biblioAnalysis(bib, sep=";")

options(width=100)
S <- summary(object = results, k=200, pause = FALSE)

```

```{r extract and clean country level data}
#isolate the country data
MostProdCountries <- print(S$MostProdCountries)
MostProdCountries$Articles <- as.numeric(MostProdCountries$Articles)
MostProdCountries$Country <- gsub("^\\s+|\\s+$", "", MostProdCountries$Country) #strip white spaces at the end
str(MostProdCountries)
MostProdCountries$Country <- as.character(MostProdCountries$Country)
```

```{r join bib to world}
#creating country column in world
str(World)
Country <- toupper(as.character(World$name))
World <- cbind(Country, World)
World$Country <- as.character(World$Country)

#matching country column in bib and world
intersect(MostProdCountries$Country, World$Country)
setdiff(MostProdCountries$Country, World$Country) #these were not matched to Countries in World data set
MostProdCountries$Country <- gsub("USA", "UNITED STATES", MostProdCountries$Country)
MostProdCountries$Country <- gsub("GUAM", "UNITED STATES", MostProdCountries$Country)
MostProdCountries$Country <- gsub("HONG KONG", "CHINA", MostProdCountries$Country)
MostProdCountries$Country <- gsub("CZECH REPUBLIC", "CZECH REP.", MostProdCountries$Country)
#MostProdCountries$Country <- gsub("BAHRAIN", "", MostProdCountries$Country) #9 lost
#MostProdCountries$Country <- gsub("MONACO", "", MostProdCountries$Country) #29 lost
#MostProdCountries$Country <- gsub("SINGAPORE", "", MostProdCountries$Country) #29 lost
#MostProdCountries$Country <- gsub("BARBADOS", "", MostProdCountries$Country) #1 lost
#MostProdCountries$Country <- gsub("BAHRAIN", "", MostProdCountries$Country) #9 lost
#MostProdCountries$Country <- gsub("MALTA", "", MostProdCountries$Country) #1 lost
#MostProdCountries$Country <- gsub("MAURITIUS", "", MostProdCountries$Country) #6 lost
#MostProdCountries$Country <- gsub("ANTIGUA", "", MostProdCountries$Country) #4 lost
#MostProdCountries$Country <- gsub("PALAU", "", MostProdCountries$Country) #1 lost
#MostProdCountries$Country <- gsub("SAINT KITTS AND NEVIS", "", MostProdCountries$Country) #1 lost
#MostProdCountries$Country <- gsub("SAMOA", "", MostProdCountries$Country) #1 lost

MostProdCountries_World <- dplyr::left_join(MostProdCountries, World, by = "Country") 
str(MostProdCountries_World)
head(MostProdCountries_World)
```

```{r proportion of research by country}
MostProdCountries_World$article_prop <- (MostProdCountries_World$Articles/9728)*100

sum(MostProdCountries_World$article_prop[1:12]) #the top 12 countries produce 50% of the research
```

```{r colour-map, fig.cap='Global marine pollution research by proportion'}

#Mapping by proportion of articles
tm_shape(MostProdCountries_World) + tm_fill(col = "article_prop")

tm_shape(World) + tm_fill()
```


```{r colour-map, fig.cap='Global marine pollution research by total articles'}

#Mapping by total number of articles
tm_shape(MostProdCountries_World) + tm_fill(col = "Articles")


```


```{r mapping by symbol}
tm_shape(MostProdCountries_World) +
  tm_polygons() +
  tm_symbols(col="blue", size = "article_prop")
```

