---
title: "mp-mapping"
author: "Brie Sherow"
date: "08/07/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

```

```{r figure-setup, echo=FALSE, include=FALSE}
knitr::opts_chunk$set(fig.path="output/", fig.width=11, fig.height=9.5, fig.align="center")
#reference:https://geocompr.robinlovelace.net/adv-map.html#static-maps
```

```{r install libraries and load data}
library(tmaptools)
library(tmap)
library(sf)
library(bibliometrix)
library(tidyverse)
data("World")
```


```{r upload data, eval=TRUE}
# getwd()
# bib <- convert2df(file = c("./data/scopus2015-2017.bib"), dbsource = "scopus", format = "bibtex") # Convert one file to bibliometric df for testing

bib <- convert2df(file = c("./data/scopus2018-2019.bib","./data/scopus2015-2017.bib", "./data/scopus2011-2014.bib","./data/scopus2006-2010.bib", "./data/scopus1999-2005.bib","./data/scopus1970-1998.bib"), dbsource = "scopus", format = "bibtex") # Convert all files to a bibliometric data frame

save(bib, file = "./data/bib.RData") #save this data frame as a RData file (object)
load(file = "./data/bib.RData") #to load this data frame from a RData file (returns an object named "bib")

# names(bib)

#write.csv(bib, "output/bib_as_df.csv", row.names = FALSE) #save this data frame as a csv file
```

```{r analysis and summary}
results <- biblioAnalysis(bib, sep=";")

save(results, file = "./data/results.RData") #save this data frame as a RData file (object)
load(file = "./data/results.RData") #to load this data frame from a RData file (returns an object named "bib")

options(width=100)
S <- summary(object = results, k=200, pause = FALSE)

```

```{r extract and process country level data}
#isolate the country data
MostProdCountries <- print(S$MostProdCountries)
MostProdCountries$Articles <- as.numeric(MostProdCountries$Articles)
MostProdCountries$Country <- gsub("^\\s+|\\s+$", "", MostProdCountries$Country) #strip white spaces at the end
str(MostProdCountries)
MostProdCountries$Country <- as.character(MostProdCountries$Country)

sum(MostProdCountries$Articles)
sum(as.numeric(MostProdCountries$Freq))


MostProdCountries
```

```{r join bib to world, echo=FALSE, include=FALSE}
#creating country column in world
str(World)
Country <- toupper(as.character(World$name))
World <- cbind(Country, World)
World$Country <- as.character(World$Country)

#matching country column in bib and world
intersect(MostProdCountries$Country, World$Country)
setdiff(MostProdCountries$Country, World$Country) #these were not matched to Countries in World data set
MostProdCountries$Country <- gsub("USA", "UNITED STATES", MostProdCountries$Country)
MostProdCountries$Country <- gsub("GUAM", "UNITED STATES", MostProdCountries$Country)
MostProdCountries$Country <- gsub("HONG KONG", "CHINA", MostProdCountries$Country) 
MostProdCountries$Country <- gsub("CZECH REPUBLIC", "CZECH REP.", MostProdCountries$Country)
# MostProdCountries$Country <- gsub("BAHRAIN", "", MostProdCountries$Country) #9 lost
# MostProdCountries$Country <- gsub("MONACO", "", MostProdCountries$Country) #29 lost
# MostProdCountries$Country <- gsub("SINGAPORE", "", MostProdCountries$Country) #29 lost
# MostProdCountries$Country <- gsub("BARBADOS", "", MostProdCountries$Country) #1 lost
# MostProdCountries$Country <- gsub("BAHRAIN", "", MostProdCountries$Country) #9 lost
# MostProdCountries$Country <- gsub("MALTA", "", MostProdCountries$Country) #1 lost
# MostProdCountries$Country <- gsub("MAURITIUS", "", MostProdCountries$Country) #6 lost
# MostProdCountries$Country <- gsub("ANTIGUA", "", MostProdCountries$Country) #4 lost
# MostProdCountries$Country <- gsub("PALAU", "", MostProdCountries$Country) #1 lost
# MostProdCountries$Country <- gsub("SAINT KITTS AND NEVIS", "", MostProdCountries$Country) #1 lost
# MostProdCountries$Country <- gsub("SAMOA", "", MostProdCountries$Country) #1 lost

MostProdCountries_World <- dplyr::left_join(World, MostProdCountries, by = "Country") 
str(MostProdCountries_World)
head(MostProdCountries_World)
```

```{r aggregate multiples}
#combine china/hongkong and usa/guam rows to avoid duplicates
countries_aggregated <- aggregate(MostProdCountries_World$Articles, by=list(Country=MostProdCountries_World$Country), FUN=sum)
str(countries_aggregated)

#rename x to Articles
names(countries_aggregated)[names(countries_aggregated)=="x"] <- "Articles"

MostProdCountries_World <- dplyr::left_join(World, countries_aggregated, by = "Country")    
```

```{r fractionalised research by country}
#creating a column for fraction of the research
sum(MostProdCountries_World$Articles, na.rm = TRUE)
MostProdCountries_World$article_percentage <- (MostProdCountries_World$Articles/sum(MostProdCountries_World$Articles, na.rm = TRUE)*100) #if you multiply this by 100, it is percentage, not proportion
#MostProdCountries_World$article_prop <- as.numeric(MostProdCountries_World$article_prop)
sum(MostProdCountries_World$article_prop, na.rm = TRUE) #1

#replacing NAs with zero
MostProdCountries_World$article_percentage[is.na(MostProdCountries_World$article_percentage)] <- 0

#checking the total
sum(MostProdCountries_World$article_percentage) #this map only represents 76.6% of the research due to lost matches above

#which countries represent the majority of the research
MostProdCountries_World %>%
  dplyr::arrange(desc(article_percentage)) %>% top_n(6, article_percentage) -> top6

# sum(top10$article_prop) #0.65
# 
# sum(top7$article_prop) #0.52
# 
# sum(top6$article_prop) #0.47
# 
# sum(top5$article_prop) #0.43
```


```{r colour-map, fig.cap='Global marine pollution research by proportion'}
#rename attribute for legend

#Mapping by proportion of articles, top 5 outlined
mp_geog <- tm_shape(MostProdCountries_World) + 
  tm_fill(col = "article_percentage", palette="BuGn", 
    style="cont", title = "Percentage of Articles") +
  tm_layout("Geography of marine pollution research",
          legend.title.size = 1,
          legend.text.size = 0.6,
          legend.position = c("left","bottom"),
          title.position = c("right", "bottom"))

tmap_save(
  tm = mp_geog,
  filename = "./figures/mp_geog.png")

#Only five countries produce more than 5% of the research each; USA, China, Spain, Italy, UK.

```


